# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
cache: packages
sudo: false
notifications:
  email:
     recipients:
        - nicholas.lauerman@gmail.com
        - nick.lauerman@abbott.com
     on_success: always
     on_failure: always
